### ISSUE TITLE
TUTORIAL: add SandroideBaseApplication and SandroideBaseActivity inheritance

### ISSUE THREAD

**Issue by giowild** [SAndroidEOfficial/framework#22]
Fix tutorials by adding SandroideBaseAcitivity inheritance in activity classes and SandroideBaseApplication in AndroidManifest.xml.

Please, read Beta 0.3 changes for more information

**Comment by giowild** [comment]
Per poter creare in automatico un messaggio ogni qualvola la libreria sandroide vada in errore, indipendentemente dall'app che sta usando effettivamente la libreria (sia questa il flasher, una app utente o la beacon-config) è stato necessario creare 2 nuove classi: SandroideApplication e SandroideBaseActivity

Questo ha una serie di conseguenze nello sviluppo delle app utente, che dovranno essere riportate all'interno dei tutorial:
- I file java delle activity delle applicazioni utente che utilizzino Sandroide, devono d'ora in poi ereditare da SandroideBaseActivity, anzichè dalle classi base Google (Activity)
- Nel file AndroidManifest.xml deve essere aggiunto al tag "application" un nuovo attributo: 
        android:name="eu.angel.bleembedded.lib.activities.SandroideApplication"
- Non è piu necessario nel metodo OnCreate della activity principale, eseguire BLEContext.init, poichè questo viene già chiamato nell'OnCreate della SandroideBaseActivity.

**Comment by RedsAnDev** [comment]
Are these changes effective from version 0.4?

**Comment by giowild** [comment]
No, they are effective from beta 0.3.

Please, read Beta 0.3 release changes for more information

**Comment by giowild** [comment]
done, this is described once for all, in the Sandroide Install Tutorial
