### ISSUE TITLE
[Broken Url]  Tutorial

### ISSUE THREAD

**Issue by RedsAnDev** [SAndroidEOfficial/framework#26]
Following step in Tutorial T1 to download SAndroidE.aar at this step

https://github.com/SAndroidEOfficial/framework/wiki/T1-Arduino-and-2-RaspBerry#sandroide-library-inclusion

I get a 404 
http://es3.unibs.it/SAndroidE/files/framework.zip

**Comment by bgkerion** [comment]
The tutorial has been fixed. You can find all the .aar into the releases page on the repository https://github.com/SAndroidEOfficial/framework/releases.
