### ISSUE TITLE
[traduction] Misleading lang

### ISSUE THREAD

**Issue by RedsAnDev** [SAndroidEOfficial/framework#27]
In **App's logic**

[https://github.com/SAndroidEOfficial/framework/wiki/T1-Arduino-and-2-RaspBerry#apps-logic](https://github.com/SAndroidEOfficial/framework/wiki/T1-Arduino-and-2-RaspBerry#apps-logic)

exists this phrase 
_inserire spiegazione suffisso rbs e raspi?! perchè e dove sono definiti?!_

**Comment by giowild** [comment]
thanks!  Fixed by removing the phrase: motivations on the suffix were out of the scope of this tutorial
