### ISSUE TITLE
[raspi3B] Where can I find image to upload?

### ISSUE THREAD

**Issue by RedsAnDev** [SAndroidEOfficial/framework#28]
Maybe I'm too lazy, but I cannot find any explicit filename or suggest for raspberry Pi 3 B-model. 
I download 0.4 and 0.1 version of SAndroidE, but I still missing which file I need for raspberry.

By Tutorial 1, I find this reference:

> ... The image of the already set up Raspberry can be found at the link reported on SAndroidE site (http://es3.unibs.it/SAndroidE/)...

So, what I wrong?

**Comment by bgkerion** [comment]
The [tutorial 1](https://github.com/SAndroidEOfficial/framework/wiki/T1-Arduino-and-2-RaspBerry) has been updated with the right URL. Thanks for report!
