### ISSUE TITLE
[raspi3B] Authentication failure @ every start - SOLVED

### ISSUE THREAD

**Issue by RedsAnDev** [SAndroidEOfficial/framework#30]
Hi, I writed right now dev-image for Raspberry3, but every start ends with
`
Raspbian GNU/Linux 8 raspberrypi tty1
raspberrypi login: pi (automatic login)
Authentication failure
`
I'm working at home, what I need to do?

I'm really sure to correctly write disk image on ssd (I follow same istructions for _raspian_, by raspberry official website).

**Comment by bgkerion** [comment]
Thanks for the feedback. We re-tested the image and everything seems to work properly. Try to re-flash the image and let we know.

**Comment by RedsAnDev** [comment]
I solve it: when I flashed image with macOS, I use path `/dev/disk#` instead `/dev/**r**disk#`. Thank you so much!
