### ISSUE TITLE
"Using RedBear Nano with SAndroidE" has no circuit schematics

### ISSUE THREAD

**Issue by Koldar** [SAndroidEOfficial/framework#33]
The tutorial called "Using RedBear Nano with SAndroidE" available at the [link](https://github.com/SAndroidEOfficial/framework/wiki/Using-RedBear-Nano-with-SAndroidE) has no circuit schematics. It would be great having one

**Comment by RedsAnDev** [comment]
I suggest to use Fritzing to draw scheme, and for redBear's parts I -googled- _found_ this repository

[https://github.com/makenai/FritzingParts](https://github.com/makenai/FritzingParts)

**Comment by giowild** [comment]
The trimmer, button and led are respectively connected to BLENano pins 4, 15, 28. These pins are then used also in java code in the tutorial.

All other wires in the picture connecting the Nano to the MK20 USB board, are only used for firmware development and deployment, as well as to power on the Nano. Yellow wires going outside of the image on the bottom are not connected!

However if firmware is stable, the MK20 USB board can be safely removed and the Nano connected only  to power and components only.

**Comment by LivingDeadCloud** [comment]
@RedsAnDev very interesting. I will add it as soon as I can.

**Comment by LivingDeadCloud** [comment]
@RedsAnDev the parts you linked unfortunately do not correspond to the components used in the tutorial.

Anyway, I managed to create an image for the mounting of the circuit.
