### ISSUE TITLE
All view in OnCreate : why?

### ISSUE THREAD

**Issue by RedsAnDev** [SAndroidEOfficial/framework#34]
Hi guys,
I'm reading wiki on How-To-**SAndroidE2RedBearNano** when I found this line

> To finish, we implement the logic for each pin always within the OnCreate method.

[wiki](https://github.com/SAndroidEOfficial/framework/wiki/Using-RedBear-Nano-with-SAndroidE#the-activity-file)

In every App I develop, I call view inside function triggered, instead all in onCreate methods.
So, does SAndroidE need some special declaration?

**Comment by giowild** [comment]
Hi Andrea,

no, it is not needed to put findViewById in the OnCreate method. You only need to be sure that you call it before actually using it :)

Maybe that line in the tutorial may generate confusion. I just removed it.
