### ISSUE TITLE
[BLEShield] Some connectivity problems

### ISSUE THREAD

**Issue by sara9521** [SAndroidEOfficial/framework#41]
Sometimes it's really hard to keep contact with Arduino+BLEShield as it continues to disconnect while flashing. We don't understand if it's a bug or a hardware problem: we tried to connect with two different Arduino+BLESh but problem remains

**Comment by giowild** [comment]
Are you trying to flash arduino with ble shield mounted? If so, you can't. First detach your ble shield and flash your arduino without it. Then mount the ble shield and use sandroide.

Please, let me know here if it works correctly
