### ISSUE TITLE
Digital Output with RedBear nano

### ISSUE THREAD

**Issue by FredWops** [SAndroidEOfficial/framework#44]
Hi guys, I have some problem with Sandroide and the RedBear nano: I would like to switch on and off a led pressing a virtual batton on my smartphone. I used the function nanoLed.setDigitalValueHigh(true) and  I put it here: public void onDigitalInputValueChanged(BLEGeneralIOEvent bleGeneralIOEvent) but it doesn't work. I searched into the tutorials but I did't found anything that could explaind how to provide a digital output with the smartphone. Could you help me. Thank you :)

**Comment by giowild** [comment]
Hi Fred,

1. in [this tutorial](https://github.com/SAndroidEOfficial/framework/wiki/Using-RedBear-Nano-with-SAndroidE), scroll down to "GENERAL_IO_DO" in the page, and copy/paste the code to initialize the led as digital output into your application. 
2. Then from another function, as example in your virtual button listener, you can call the *setDigitalValueHigh* method in this way:

```
        myButton=(Button) findViewById(R.id.myButton);
        myButton.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View v) {
                                   nanoLed.setDigitalValueHigh(true);
			}
		});
```
