### ISSUE TITLE
Set of sampling interval and hysteresis to read pins

### ISSUE THREAD

**Issue by giowild** [SAndroidEOfficial/framework#47]
Currently the sampling period to check if a pin value is changed, is a fixed value (e.g. 200ms in nano firmware, other value in arduino, etc.). Moreover, the thresold at which the value is considered changed, and that means it must be sent to smartphone, is also fixed.

It would be nice to let the app developer configure these values using Sandroide.

Should these values be unique for all pins or each pin may have its own values? 

Creating a pair for each pins is not easy on the firmware side, because it means one of these two:
* using different timer objects for each pin: feasibility should be checked
* or a unique fast timer for all pins (let's say 1ms), and a loop to detect if pin needs to be checked (N slots of time have passed). drawback: resource intensive.

**Comment by giowild** [comment]
@drkangel what you think is the best way to achieve it?

**Comment by drkangel** [comment]
The first option is surely the best one... but you should check if the library used to create the FWs for the different remote device makes it available, and if it's feasible creating so many timers on devices with poor resources. The second option is not necessarily energy-intensive if you conveniently set the available periods (for example the t2=2*t1 t3=2*t2 etc. using as basetime the shorter period choosen from the user). From the SandroidE library point of view a set of new functions for the BLEGPIO Object to handle this new feature could be added.

**Comment by giowild** [comment]
> for example the t2=2t1 t3=2t2 etc.

nice idea!

**Comment by giowild** [comment]
ok, done in Beta 0.7
