### ISSUE TITLE
Flasher app needs permission ACCESS_COARSE_LOCATION ?! in Android 6

### ISSUE THREAD

**Issue by giowild** [SAndroidEOfficial/framework#8]
When installing flasher app on a new smartphone, the app starts but devices aren't shown in "Scan devices". An error is raised on the log: app needs ACCESS_COARSE_LOCATION.

We had to enable location permission manually from app manager, to let the flasher app work. 

TODO: Implement a way to let the app notify/asks the user for authorization if it is not already granted

**Comment by bgkerion** [comment]
@giowild check if this question is still valid after the insertion of #21. Please close otherwise... thanks ;)

**Comment by giowild** [comment]
@bgkerion: yes, this is still valid. Taking flasher features inside activities, should only move the permission issue from support applications to the user app. However this permission issue will be fixed in Beta 0.3
